### ISSUE TITLE
想问下remesh的domain可以支持继承吗？

### ISSUE THREAD

**Issue by Excalibur0w0** [remesh-js/remesh#66]
比如 定义了一个Domain叫 AnimalDomain,  我想对它进行不同的实现，然后在另外一个ManageDomain中引用AnimalDomain, 根据注入的参数不同，让AnimalDomain呈现为不同的子实现。目前似乎我只能通过引用不同的Domain来实现，或者借助map

**Comment by Lucifier129** [comment]
不支持继承。可以通过 custom module 以组合的方式来达到相同目的。

类似 AsyncModule 可以用在多个 domain 中。
