### ISSUE TITLE
如何从command中获取到一个返回值？

### ISSUE THREAD

**Issue by FlyingLxy** [remesh-js/remesh#67]
比如我有一个CreateCommand，我需要返回创建之后的id用于后续异步的继续对这个id资源做某些操作。

**Comment by hourong88** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！

**Comment by Lucifier129** [comment]
command 不负责返回数据，可以在调用 command 后，用query 去查询当前 state。

也可以用 domain event 领域事件，如 CreatedEvent<EventData> ，在 async-module、 domain effect 或者外部订阅函数中，处理异步资源。

**Comment by FlyingLxy** [comment]
> command 不负责返回数据，可以在调用 command 后，用query 去查询当前 state。
> 
> 也可以用 domain event 领域事件，如 CreatedEvent ，在 async-module、 domain effect 或者外部订阅函数中，处理异步资源。

好吧，谢谢
