### ISSUE TITLE
同一个AsyncModule 同时（连续）调用多次，只会触发一次onSuccess

### ISSUE THREAD

**Issue by FlyingLxy** [remesh-js/remesh#68]
场景：
获取多个对话的会话列表
每一个会话调用一次 LoadMessageByConversationIdAsyncModule

load会执行多次，onSuccess只会执行一次。
如果中间某一次出现异常，则只会执行一次onFailed，不会执行任何一次onSuccess

![image](https://user-images.githubusercontent.com/13180768/207701840-4b9bd9ed-940d-4444-867e-4378bf197f6e.png)

**Comment by Lucifier129** [comment]
这是因为 `async-module` 默认是 `switch mode`，反复发送会取消前一次的。

可以设置 `options.mode` 为 `merge`，背后就会采用 rxjs 的 `mergeMap`，每次都是独立的。如果想要按照调用顺序来输出，则可以设置为 `concat` 模式。

**Comment by FlyingLxy** [comment]
> 

好的，谢谢
