### ISSUE TITLE
中文文档有误

### ISSUE THREAD

**Issue by C-zhui** [remesh-js/remesh#81]
README_zh_CN.md 
特性第5：可变状态
英文版是，immutable state
应该是，不可变状态

**Comment by Lucifier129** [comment]
@C-zhui 好的，感谢提醒~如果可以提个 PR 修复这个问题就更好啦~

**Comment by ninesunsabiu** [comment]
顺便的，  HOW-TO 中也有一些变量的使用错误，中英均有

https://github.com/remesh-js/remesh/blob/a092095129063598bd9cbd77cc71e22bbb3757f1/docs/how-to-guide.md?plain=1#L890-L900

~~AQuery.emitted~~ -> AEvent. emitted
