### ISSUE TITLE
要是有个交流群或者discord就好了

### ISSUE THREAD

**Issue by yuyi919** [remesh-js/remesh#82]
感觉remesh的设计很有前景，但没发现有什么交流渠道

**Comment by Lucifier129** [comment]
有个微信群，可扫描加入~

![0zm2c12000bn8qdd5F4C5](https://github.com/remesh-js/remesh/assets/6636455/07600b11-852d-4bc3-ab04-64f0c6e01231)

**Comment by molvqingtai** [comment]
过期了，可以再发一遍吗

**Comment by Lucifier129** [comment]
![0zm5p12000bup0iws7E53](https://github.com/remesh-js/remesh/assets/6636455/3aeb33b8-d5e5-4bcb-8e81-2514006248bb)

**Comment by soakit** [comment]
过期了又。留下个人的二维码吧

**Comment by Lucifier129** [comment]
![微信图片_20230922220414](https://github.com/remesh-js/remesh/assets/6636455/bbc96a63-a7bd-4606-84be-96ed9f31761e)

**Comment by miser** [comment]
求一个二维码

**Comment by hourong88** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！
