### ISSUE TITLE
query的类型没有自推倒，那类型如何定义？

### ISSUE THREAD

**Issue by soakit** [remesh-js/remesh#88]

**Comment by soakit** [comment]
![image](https://github.com/remesh-js/remesh/assets/11240668/f15dd8d4-34b6-4c61-948d-f88cb1b944c1)

将query, command, events都独立文件处理，以免domain过大。但这样query的类型就变成any了

**Comment by soakit** [comment]
![image](https://github.com/remesh-js/remesh/assets/11240668/f0e6640c-b5aa-4db0-ade5-4526e3d9e8ae)

想将query, command, events都独立文件处理，避免domain文件太大，有没有好的解决方案？

**Comment by Lucifier129** [comment]
理论上不会产生这个问题，需要检查一下 `getQueries` 自身的类型定义是否健全

**Comment by soakit** [comment]
![image](https://github.com/remesh-js/remesh/assets/11240668/f19c90d1-6b39-4689-b541-d902dc3c7667)
还有一个问题，这个传入的`events`的类型怎么获取？

**Comment by Lucifier129** [comment]
你的截图里的代码，有很多不规范的地方。

获取 events 类型其实很简单，只要在编辑器里 hover 上去查看一个普通 event 的类型，复制出来组成一个 object type 即可。

你的场景其实是要定义一个 Remesh Modules，一般做法如下：

```ts
import { Remesh, RemeshCommandOutput, RemeshDomainContext } from 'remesh'

type Buyer = {

}

type OrderState = {
  buyer: Buyer
}

/**
 * 用 getters, setters and callbacks
 * 不要直接依赖具体的 domain 对象
 */
type BuyerModuleOptions = {
  onBuyerUpdated: () => RemeshCommandOutput
}

const BuyerModule = (domain: RemeshDomainContext, options: BuyerModuleOptions) => {
  const OrderState = domain.state({
    name: 'OrderState',
    default: {}
  })


  const BuyerUpdatedEvent = domain.event({
    name: 'BuyerUpdatedEvent',
  })

  const UpdateBuyerCommand = domain.command({
    name: 'UpdateBuyerCommand',
    impl: ({ get }, buyer: Buyer) => {
      const newState = {
        ...get(OrderState),
        buyer
      }

      return [
        OrderState.new(newState),
        BuyerUpdatedEvent(),
        options.onBuyerUpdated()
      ]
    }
  })


  return {
    command: {
      UpdateBuyerCommand
    },
    event: {
      BuyerUpdatedEvent
    }
  }
}

```

类型推导如下：

![image](https://github.com/remesh-js/remesh/assets/6636455/68a71a41-faa1-4fb7-bd82-f77f99aa6279)

**Comment by soakit** [comment]
这里再拆分一个`BuyerModule`，理解到了。但我的想法是当成员比较小时，不必单独拆分。

之前的问题，单个`domain`怎么去拆分它的query, command, event, effect作为文件独立管理，一个简单的[todoDomain](https://github.com/remesh-js/remesh/blob/main/projects/domains/src/todo-mvc/index.ts)，也有240多行的代码，如何避免`domain`文件太长难以阅读、多人协作的文件冲突等，如何解决请指教。

[示例代码](https://codesandbox.io/s/remesh-m9w99h?file=/src/domains/order/index.ts)

**Comment by Lucifier129** [comment]
240 行的 todo domain 是正常的，文件长不意味着一定会难以阅读，还是要看代码自身的复杂度。多人协作文件冲突按照 git 的方式解决。

单个 domain 也不必按照 query, command, event, effect 的分类进行拆分，而是按照 feature 来拆分，一个 feature 可以有自己的一套 query, command, event ,effect，按照上面示意过的 `Remesh Module` 的风格进行设计和封装。跟 react component 通过 react hooks 拆分出去是一样的。

[todo domain](https://github.com/remesh-js/remesh/tree/main/projects/domains/src/todo-mvc-with-multiple-domains/domains) 这里有个拆分版的 todo domain，总体代码更长，但更灵活和解耦。
