### ISSUE TITLE
Module not found: Error: Can't resolve 'use-sync-external-store/shim' in '/project/remesh-example/node_modules/remesh-react/esm'

### ISSUE THREAD

**Issue by soakit** [remesh-js/remesh#89]
![image](https://github.com/remesh-js/remesh/assets/11240668/2a143c24-1ca5-40b0-8eb5-c9ec83812018)

**Comment by Lucifier129** [comment]
这个是已知问题，remesh-react 以 esm 形式被使用，但 react 的一个包是 cjs 的。可以用 4.0 最新版本，默认 cjs 输出。

或者使用 `remesh-react/cjs` 指定使用 cjs 版本。
