### ISSUE TITLE
ListModule 暴露 event 的必要性？

### ISSUE THREAD

**Issue by ScarboroughCoral** [remesh-js/remesh#90]
在看 [TodoList example](https://github.com/remesh-js/remesh/blob/f3c117aa1f57be44c7c250a86b2fb2c1abca8e96/projects/domains/src/todo-mvc-with-multiple-domains/domains/TodoList.ts#L33) 时发现`event`产生依赖于`TodoListModule`的`command`，但是 `command` 实现细节是在`remesh` 内部的，需要使用者确定`command`确实对`list`产生了修改，如果`ListModule`对外暴露`ListChangedEvent、ListItemAddedEvent`等事件，外部就确定事件已发生可以直接使用。不知道有没有必要呢？如果有必要的话我想尝试提一下pr～
<img width="734" alt="image" src="https://github.com/remesh-js/remesh/assets/26180429/edf59107-bdc7-4773-b7f1-b4a777a60cdc">

**Comment by hourong88** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！

**Comment by Lucifier129** [comment]
@ScarboroughCoral `ListModule` 不暴露 Event 是已知的问题。最初是添加了 ItemAddedEvent, ItemDeletedEvent, ListChangedEvent 等事件，但后面发现，这些事件无法可靠地触发，因为 SetListCommand 可以将 List 整体替换，其中有些可能是 add 的新元素，有些可能是 delete 了，而有些可能 re-order 了。

这将导致业务逻辑依赖 ItemAddEvent 时，有些不是通过 AddItemCommand 添加的 added items 可能不会触发。

正因如此，remesh 才意欲引入 `entity-component-system` 和 `entity-relationship model`  等模型，掌控底层 state 的表征方式，以便得到更可靠的 state related events。

目前的折衷做法是，ListModule 自身不暴露 event，由上层 domain 自己管理自己的 event 并保证它们的可靠性。后续 remesh 升级后或许会克服这类问题。

**Comment by ScarboroughCoral** [comment]
好的 确实是这样 了解了
