### ISSUE TITLE
clearDomainStorageIfNeeded 清理之前可以有一个保留时间吗

### ISSUE THREAD

**Issue by C-zhui** [remesh-js/remesh#91]
我觉得这是一个场景，一个 domain 有多个实例，不可能都用 RemeshDomainHolderContainer 保活，但也允许存活一段时间，一段时间后再进行清理，这期间再次挂载可以复用。

**Comment by Lucifier129** [comment]
这个保活其实可以 bubble up 到上层领域处理，比如问题转变为组件的保活，或者其它订阅者的保活；这样对于 remesh 来说，它的规则可以保持简单和可预测。

**Comment by C-zhui** [comment]
场景复杂一些的时候，不太想费力去做组件保活，关键的保活时长也不好控制，还是希望能力下沉呢 哈哈哈

**Comment by Lucifier129** [comment]
上层领域掌握更多信息和条件都不好控制，remesh 更不知道用户想要维持多少时间，是否需要 debouncing, throttle， cancel, switch 等。
