### ISSUE TITLE
Remesh-js 有什么方便的调试工具吗？ // Any dev tools available for remesh-js?

### ISSUE THREAD

**Issue by AnteeHub** [remesh-js/remesh#96]
一些 react 的状态库有相关的 dev tools，比如：
redux -> [redux-devtools](https://github.com/reduxjs/redux-devtools)
mobx -> [mobx-react-devtools](https://github.com/mobxjs/mobx-react-devtools)
remesh-js 有自己的调试工具吗？或者是有推荐用于调试的 dev tools 吗？

Some libraries are used to manage react status have  their dev tools, such as:
redux -> [redux-devtools](https://github.com/reduxjs/redux-devtools)
mobx -> [mobx-react-devtools](https://github.com/mobxjs/mobx-react-devtools)
Do you know if remesh-js has its dev tools? Or any other recommended dev tools to use for debugging?

**Comment by hourong88** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！

**Comment by Lucifier129** [comment]
[如何连接到 redux-devtools?](https://github.com/remesh-js/remesh/blob/main/docs/how-to-guide_zh_CN.md#%E5%A6%82%E4%BD%95%E8%BF%9E%E6%8E%A5%E5%88%B0-redux-devtools)

remesh 支持接入 devtools 查看 command history
